#!/usr/bin/env python
# coding: utf-8

# # SIMPLE SEDML VINGNETTE

# **To do**
# 1. Example of stochastic time course
# 2. Parameter scans: one-step, steady-state
# 3. Example of mixing low-level API and task API.

# This notebook provides examples of using ``SimpleSBML``.
# 
# The initial emphasize is on time course simulations. A ``SingleModelTimeCourse`` object has one required parameter, the model. This can be an Antimony or SBML string or file or a URL. There are optional parameters related to the simulation and changing values of the paramters of the model. It has the following methods:
# * ``getSEDML``
# * ``getPhraSEDML``
# * ``execute``: returns a ``DataFrame`` and a plot of the variables specified in the constructor.
# * ``makeOMEXFile`` creates an omex file
# 
# A ``MultipleModelTimeCourseObject`` has the same arguments as for ``SingleModelTimeCourse`` except that the one required argument is a list of models. It has the same methods as well. The only difference is that there is one plot for each variable specified in the constructor with a curve for each model.
# 
# Some use cases are:
# 1. Iteratively develop SEDML by use execute, and then generate desired SEDML.
# 2. Generate PhraSEDML, edit it, and then generate SEDML from these edits.

# In[1]:


# In[2]:

import SimpleSEDML as ss  # type: ignore
import pandas as pd # type: ignore


# Collect paths of files creates
MODEL_SOURCES:list = []


# # Model

# In[3]:


MODEL_ANT = '''
model myModel
    J1: S1 -> S2; k1*S1
    J2: S2 -> S3; k2*S2
    
    S1 = 10
    S2 = 0
    k1 = 1
    k2 = 1

    S1 is "species1"
    S2 is "species2"
end
'''


# In[4]:


MODEL2_ANT = '''
model myModel
    J1: S1 -> S2; k1*S1
    J2: S2 -> S3; k2*S2
    J3: S3 -> S1; k3*S3
    
    S1 = 10
    S2 = 0
    k1 = 1
    k2 = 1
    k3 = 0.1
end
'''


# # Use Case 1: Single model with default arguments

# In[5]:



# In[6]:


smtc = ss.makeSingleModelTimeCourse(MODEL_ANT, title="My Plot", num_point=100)


# In[7]:


print(smtc.getPhraSEDML())


# In[8]:


print(smtc.getSEDML())


# We can also look at the PhraSED-ML that gets generated by changing the object that gets returned.

# In[9]:


print(smtc.getPhraSEDML())


# And we can execute the SEDML, getting both a plot and a DataFrame of time course values.

# In[10]:


df = smtc.execute()


# In[11]:


df.head()


# In[12]:


# Eliminate the temporary files
smtc.cleanUp()


# # Use Case 2: Single model with non-default arguments

# In[13]:


WOLF_URL = "https://www.ebi.ac.uk/biomodels/services/download/get-files/MODEL3352181362/3/BIOMD0000000206_url.xml"


# In[14]:


smtc = ss.makeSingleModelTimeCourse(WOLF_URL, num_point=1000)
_ = smtc.execute()


# In[15]:


ss.getModelInformation(WOLF_URL)


# In[16]:


smtc = ss.makeSingleModelTimeCourse(WOLF_URL, model_parameter_dct=dict(k0=5, k1=55),
            title="Wolf with new parameter values")
df = smtc.execute()


# In[17]:


df.head()


# In[18]:


smtc.cleanUp()


# # Use Case 3: Comparing the time course simulation of multiple models

# When comparing the time course simulation of multiple models, we want to compare selected **display variables** from the models, either in plots or in a DataFrame. This is done with the  ``MultipleModelTimeCourse`` object.

# In[19]:


mmtc = ss.makeMultipleModelTimeCourse([MODEL_ANT, MODEL2_ANT], model_parameter_dct=dict(k1=10), num_point=100)


# In[20]:


print(mmtc.getSEDML())


# In[21]:


mmtc.execute()


# In[22]:


mmtc.model_dct


# In[23]:


print(mmtc.getPhraSEDML())


# ## Creating an OMEX file

# We can create an OMEX file for this experiment.

# In[24]:


omex_path, _ = mmtc.makeOMEXFile()


# In[25]:



# In[26]:


mmtc.cleanUp()


# # Case 4: Parameter Scans: onestep and steadystate

# ## Single Model Parameter Scan

# In[27]:


smps = ss.makeSingleModelParameterScan(WOLF_URL, simulation_type="onestep",
                                       project_id="Wolf", title="Wolf",
        time_interval=10, display_variables=["at", "na"], scan_parameter_dct=dict(k1=[50, 550, 5000]))
print(smps.getPhraSEDML())
_ = smps.execute()


# ## Multiple Model Parameter Scan

# In[28]:

"""
mmps = ss.makeMultipleModelParameterScan([], simulation_type="onestep",
        project_id="Wolf", title="Wolf",
        time_interval=10, display_variables=['at', 'na'],
        #scan_parameter_df=pd.DataFrame(dict(k1=[50, 550, 5000]))
        )
"""
scan_parameter_df = pd.DataFrame(dict(k1=[50, 550, 5000]))
mmps = ss.makeMultipleModelParameterScan(scan_parameter_df,
                                         model_refs=[WOLF_URL],
                                         simulation_type="onestep",
                                         project_id="Wolf", 
                                         title="Wolf",
                                         time_interval=10, 
                                         display_variables=['at', 'na'])


# In[29]:


_ = mmps.addModel("k0_1", WOLF_URL, parameter_dct=dict(k0=1))
_ = mmps.addModel("k0_25", WOLF_URL, parameter_dct=dict(k0=25))
_ = mmps.addModel("k0_600", WOLF_URL, parameter_dct=dict(k0=600))
_ = mmps.addModel("k0_6000", WOLF_URL, parameter_dct=dict(k0=6000))


# In[30]:


#print(smps.getPhraSEDML())
_ = mmps.execute()


# # Under construction: Compare several parameters at steady state for a single model

# # Under construction: Compare stochastic simulations

# # Under construction: Repeated Tasks

# At present, the Tellurium execution of SED-ML only provides access to the last report for repeated tasks.

# In[31]:


# Make DataFrame of changes to model parameters
parameter_df = pd.DataFrame(dict(k1=[1, 3], k2=[1, 3]))


# In[32]:


ssed = ss.SimpleSEDML()
ssed.addModel("model1", MODEL_ANT, parameter_dct=dict(k1=3), ref_type="ant_str", is_overwrite=True)
ssed.addSimulation("sim1", "uniform", start=0, end=1, num_step=50)
ssed.addTask("task1", "model1", "sim1")
ssed.addRepeatedTask("repeated_task1", "task1", parameter_df=parameter_df)
ssed.addReport("task1.time", "task1.S1", "task1.S2", "task1.S3")
ssed.addPlot("repeated_task1.time", "repeated_task1.S2", title="my plot")
result_df = ssed.execute()


# In[33]:


print(ssed.getSEDML())


# In[34]:


ssed.cleanUp()


# # Cleanup

# In[35]:


import os
EXAMPLE_REMOVE_FILES = ["simple_sedml_plot.png", "project.omex", "project.omex"]
example_dir = os.getcwd()
remove_files = [os.path.join(example_dir, f) for f in EXAMPLE_REMOVE_FILES]
remove_files.extend(MODEL_SOURCES)
for ffile in remove_files:
    if os.path.isfile(ffile):
        os.remove(ffile)

