name: Continous integration
on: [push]
jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.12'
    - name: Install
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Run tests
      run: |
        python -m pytest src/tests/ -v
    - name: Run notebook
      run: |
        pip install -r requirements_dev.txt
        python scripts/convert_notebook_to_script.py
        ipython examples/vingnette.py
    - name: Create wheel
      run: |
        python -m build --wheel
    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: SimpleSEDML-python-wheel
        path: dist/*whl
